// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.1
// - protoc             v5.28.3
// source: proto/studio.proto

package studio

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationStudioRemoteServiceFindStudio = "/gnboot.StudioRemoteService/FindStudio"

type StudioRemoteServiceHTTPServer interface {
	FindStudio(context.Context, *FindStudioRequest) (*FindStudioResp, error)
}

func RegisterStudioRemoteServiceHTTPServer(s *http.Server, srv StudioRemoteServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/studio/query/all", _StudioRemoteService_FindStudio0_HTTP_Handler(srv))
}

func _StudioRemoteService_FindStudio0_HTTP_Handler(srv StudioRemoteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FindStudioRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStudioRemoteServiceFindStudio)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FindStudio(ctx, req.(*FindStudioRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FindStudioResp)
		return ctx.Result(200, reply)
	}
}

type StudioRemoteServiceHTTPClient interface {
	FindStudio(ctx context.Context, req *FindStudioRequest, opts ...http.CallOption) (rsp *FindStudioResp, err error)
}

type StudioRemoteServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewStudioRemoteServiceHTTPClient(client *http.Client) StudioRemoteServiceHTTPClient {
	return &StudioRemoteServiceHTTPClientImpl{client}
}

func (c *StudioRemoteServiceHTTPClientImpl) FindStudio(ctx context.Context, in *FindStudioRequest, opts ...http.CallOption) (*FindStudioResp, error) {
	var out FindStudioResp
	pattern := "/studio/query/all"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStudioRemoteServiceFindStudio))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
