// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: proto/studio.proto

package studio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StudioRemoteService_FindStudio_FullMethodName = "/gnboot.StudioRemoteService/FindStudio"
)

// StudioRemoteServiceClient is the client API for StudioRemoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudioRemoteServiceClient interface {
	FindStudio(ctx context.Context, in *FindStudioRequest, opts ...grpc.CallOption) (*FindStudioResp, error)
}

type studioRemoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudioRemoteServiceClient(cc grpc.ClientConnInterface) StudioRemoteServiceClient {
	return &studioRemoteServiceClient{cc}
}

func (c *studioRemoteServiceClient) FindStudio(ctx context.Context, in *FindStudioRequest, opts ...grpc.CallOption) (*FindStudioResp, error) {
	out := new(FindStudioResp)
	err := c.cc.Invoke(ctx, StudioRemoteService_FindStudio_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudioRemoteServiceServer is the server API for StudioRemoteService service.
// All implementations must embed UnimplementedStudioRemoteServiceServer
// for forward compatibility
type StudioRemoteServiceServer interface {
	FindStudio(context.Context, *FindStudioRequest) (*FindStudioResp, error)
	mustEmbedUnimplementedStudioRemoteServiceServer()
}

// UnimplementedStudioRemoteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStudioRemoteServiceServer struct {
}

func (UnimplementedStudioRemoteServiceServer) FindStudio(context.Context, *FindStudioRequest) (*FindStudioResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindStudio not implemented")
}
func (UnimplementedStudioRemoteServiceServer) mustEmbedUnimplementedStudioRemoteServiceServer() {}

// UnsafeStudioRemoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudioRemoteServiceServer will
// result in compilation errors.
type UnsafeStudioRemoteServiceServer interface {
	mustEmbedUnimplementedStudioRemoteServiceServer()
}

func RegisterStudioRemoteServiceServer(s grpc.ServiceRegistrar, srv StudioRemoteServiceServer) {
	s.RegisterService(&StudioRemoteService_ServiceDesc, srv)
}

func _StudioRemoteService_FindStudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindStudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudioRemoteServiceServer).FindStudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudioRemoteService_FindStudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudioRemoteServiceServer).FindStudio(ctx, req.(*FindStudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudioRemoteService_ServiceDesc is the grpc.ServiceDesc for StudioRemoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudioRemoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gnboot.StudioRemoteService",
	HandlerType: (*StudioRemoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindStudio",
			Handler:    _StudioRemoteService_FindStudio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/studio.proto",
}
