// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/liluoliluoli/gnboot/internal/adaptor"
	"github.com/liluoliluoli/gnboot/internal/conf"
	"github.com/liluoliluoli/gnboot/internal/repo"
	"github.com/liluoliluoli/gnboot/internal/server"
	"github.com/liluoliluoli/gnboot/internal/service"
	"github.com/liluoliluoli/gnboot/internal/task/i4k"
)

import (
	_ "github.com/go-cinch/common/plugins/gorm/filter"
	_ "github.com/go-cinch/common/plugins/kratos/encoding/yml"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(c *conf.Bootstrap) (*kratos.App, func(), error) {
	universalClient, err := repo.NewRedis(c)
	if err != nil {
		return nil, nil, err
	}
	tenant, err := repo.NewDB(c)
	if err != nil {
		return nil, nil, err
	}
	sonyflake, err := repo.NewSonyflake(c)
	if err != nil {
		return nil, nil, err
	}
	tracerProvider, err := repo.NewTracer(c)
	if err != nil {
		return nil, nil, err
	}
	data, cleanup := repo.NewData(universalClient, tenant, sonyflake, tracerProvider)
	movieRepo := repo.NewMovieRepo(data)
	genreRepo := repo.NewGenreRepo(data)
	videoGenreMappingRepo := repo.NewVideoGenreMappingRepo(data)
	actorRepo := repo.NewActorRepo(data)
	videoActorMappingRepo := repo.NewVideoActorMappingRepo(data)
	studioRepo := repo.NewStudioRepo(data)
	videoStudioMappingRepo := repo.NewVideoStudioMappingRepo(data)
	keywordRepo := repo.NewKeywordRepo(data)
	videoKeywordMappingRepo := repo.NewVideoKeywordMappingRepo(data)
	videoSubtitleMappingRepo := repo.NewVideoSubtitleMappingRepo(data)
	userRepo := repo.NewUserRepo(data)
	videoUserMappingRepo := repo.NewVideoUserMappingRepo(data)
	movieService := service.NewMovieService(c, movieRepo, genreRepo, videoGenreMappingRepo, actorRepo, videoActorMappingRepo, studioRepo, videoStudioMappingRepo, keywordRepo, videoKeywordMappingRepo, videoSubtitleMappingRepo, userRepo, videoUserMappingRepo)
	movieProvider := adaptor.NewMovieProvider(movieService)
	episodeService := service.NewEpisodeService(c, movieRepo, genreRepo, videoGenreMappingRepo, actorRepo, videoActorMappingRepo, studioRepo, videoStudioMappingRepo, keywordRepo, videoKeywordMappingRepo, videoSubtitleMappingRepo)
	episodeProvider := adaptor.NewEpisodeProvider(episodeService)
	seasonService := service.NewSeasonService(c, movieRepo, genreRepo, videoGenreMappingRepo, actorRepo, videoActorMappingRepo, studioRepo, videoStudioMappingRepo, keywordRepo, videoKeywordMappingRepo, videoSubtitleMappingRepo)
	seasonProvider := adaptor.NewSeasonProvider(seasonService)
	seriesRepo := repo.NewSeriesRepo(data)
	seasonRepo := repo.NewSeasonRepo(data)
	episodeRepo := repo.NewEpisodeRepo(data)
	seriesService := service.NewSeriesService(c, seriesRepo, genreRepo, videoGenreMappingRepo, actorRepo, videoActorMappingRepo, studioRepo, videoStudioMappingRepo, keywordRepo, videoKeywordMappingRepo, videoSubtitleMappingRepo, seasonRepo, episodeRepo, videoUserMappingRepo)
	seriesProvider := adaptor.NewSeriesProvider(seriesService)
	genreService := service.NewGenreService(c, genreRepo)
	genreProvider := adaptor.NewGenreProvider(genreService)
	studioService := service.NewStudioService(c, studioRepo)
	studioProvider := adaptor.NewStudioProvider(studioService)
	keywordService := service.NewKeywordService(c, keywordRepo)
	keywordProvider := adaptor.NewKeywordProvider(keywordService)
	actorService := service.NewActorService(c, actorRepo)
	actorProvider := adaptor.NewActorProvider(actorService)
	grpcServer := server.NewGRPCServer(c, movieProvider, episodeProvider, seasonProvider, seriesProvider, genreProvider, studioProvider, keywordProvider, actorProvider)
	httpServer := server.NewHTTPServer(c, movieProvider, episodeProvider, seasonProvider, seriesProvider, genreProvider, studioProvider, keywordProvider, actorProvider)
	i4kSyncTask := i4k.NewI4kSyncTask(c, movieService)
	job := server.NewJob(c, i4kSyncTask)
	app := newApp(grpcServer, httpServer, job)
	return app, func() {
		cleanup()
	}, nil
}
