// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/episode.proto

package episode

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Episode with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Episode) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Episode with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in EpisodeMultiError, or nil if none found.
func (m *Episode) ValidateAll() error {
	return m.validate(true)
}

func (m *Episode) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for VideoId

	// no validation rules for Episode

	// no validation rules for EpisodeTitle

	// no validation rules for Url

	// no validation rules for Platform

	// no validation rules for Ext

	// no validation rules for Duration

	for idx, item := range m.GetSubtitles() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, EpisodeValidationError{
						field:  fmt.Sprintf("Subtitles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, EpisodeValidationError{
						field:  fmt.Sprintf("Subtitles[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return EpisodeValidationError{
					field:  fmt.Sprintf("Subtitles[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return EpisodeMultiError(errors)
	}

	return nil
}

// EpisodeMultiError is an error wrapping multiple validation errors returned
// by Episode.ValidateAll() if the designated constraints aren't met.
type EpisodeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EpisodeMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EpisodeMultiError) AllErrors() []error { return m }

// EpisodeValidationError is the validation error returned by Episode.Validate
// if the designated constraints aren't met.
type EpisodeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EpisodeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EpisodeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EpisodeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EpisodeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EpisodeValidationError) ErrorName() string { return "EpisodeValidationError" }

// Error satisfies the builtin error interface
func (e EpisodeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEpisode.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EpisodeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EpisodeValidationError{}

// Validate checks the field values on GetEpisodeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetEpisodeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEpisodeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEpisodeRequestMultiError, or nil if none found.
func (m *GetEpisodeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEpisodeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetEpisodeRequestMultiError(errors)
	}

	return nil
}

// GetEpisodeRequestMultiError is an error wrapping multiple validation errors
// returned by GetEpisodeRequest.ValidateAll() if the designated constraints
// aren't met.
type GetEpisodeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEpisodeRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEpisodeRequestMultiError) AllErrors() []error { return m }

// GetEpisodeRequestValidationError is the validation error returned by
// GetEpisodeRequest.Validate if the designated constraints aren't met.
type GetEpisodeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEpisodeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEpisodeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEpisodeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEpisodeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEpisodeRequestValidationError) ErrorName() string {
	return "GetEpisodeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetEpisodeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEpisodeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEpisodeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEpisodeRequestValidationError{}

// Validate checks the field values on UpdateBoxIpsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateBoxIpsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateBoxIpsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateBoxIpsRequestMultiError, or nil if none found.
func (m *UpdateBoxIpsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateBoxIpsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateBoxIpsRequestMultiError(errors)
	}

	return nil
}

// UpdateBoxIpsRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateBoxIpsRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateBoxIpsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateBoxIpsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateBoxIpsRequestMultiError) AllErrors() []error { return m }

// UpdateBoxIpsRequestValidationError is the validation error returned by
// UpdateBoxIpsRequest.Validate if the designated constraints aren't met.
type UpdateBoxIpsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateBoxIpsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateBoxIpsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateBoxIpsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateBoxIpsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateBoxIpsRequestValidationError) ErrorName() string {
	return "UpdateBoxIpsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateBoxIpsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateBoxIpsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateBoxIpsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateBoxIpsRequestValidationError{}
