// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/golang-module/carbon/v2"
)

const TableNameAppVersion = "app_version"

// AppVersion 应用版本
type AppVersion struct {
	ID                 uint64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id,string"`         // 主键
	TagName            string          `gorm:"column:tag_name;not null;comment:版本名称，1.0.0三位" json:"tagName"`                // 版本名称，1.0.0三位
	PublishedAt        carbon.DateTime `gorm:"column:published_at;not null;comment:发布时间" json:"publishedAt"`                // 发布时间
	Body               string          `gorm:"column:body;comment:备注" json:"body"`                                          // 备注
	Name               string          `gorm:"column:name;not null;comment:资源名称" json:"name"`                               // 资源名称
	BrowserDownloadURL string          `gorm:"column:browser_download_url;not null;comment:下载地址" json:"browserDownloadUrl"` // 下载地址
}

// TableName AppVersion's table name
func (*AppVersion) TableName() string {
	return TableNameAppVersion
}
