// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEpisodeAudioMapping = "episode_audio_mapping"

// EpisodeAudioMapping mapped from table <episode_audio_mapping>
type EpisodeAudioMapping struct {
	ID        int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	EpisodeID int64  `gorm:"column:episode_id;type:bigint;not null;comment:集id" json:"episodeId"`
	URL       string `gorm:"column:url;type:varchar(4096);not null;comment:音频地址" json:"url"`
	Title     string `gorm:"column:title;type:varchar(1024);not null;comment:音频标题" json:"title"`
	Language  string `gorm:"column:language;type:varchar(32);not null;comment:音频语言" json:"language"`
	MimeType  string `gorm:"column:mime_type;type:varchar(256);not null;comment:音频格式" json:"mimeType"`
}

// TableName EpisodeAudioMapping's table name
func (*EpisodeAudioMapping) TableName() string {
	return TableNameEpisodeAudioMapping
}
