// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEpisode = "episode"

// Episode mapped from table <episode>
type Episode struct {
	ID         int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	SeasonID   int64     `gorm:"column:season_id;type:bigint;not null;comment:季id" json:"seasonId"`
	Episode    int32     `gorm:"column:episode;type:int;not null;comment:第几集" json:"episode"`
	SkipIntro  *int32    `gorm:"column:skip_intro;type:int;comment:片头跳过秒数" json:"skipIntro"`
	SkipEnding *int32    `gorm:"column:skip_ending;type:int;comment:片尾跳过秒数" json:"skipEnding"`
	URL        string    `gorm:"column:url;type:varchar(1024);not null;comment:影片地址" json:"url"`
	Downloaded int32     `gorm:"column:downloaded;type:tinyint;not null;comment:是否能下载" json:"downloaded"`
	Ext        *string   `gorm:"column:ext;type:varchar(1024);comment:扩展参数" json:"ext"`
	FileSize   *int32    `gorm:"column:file_size;type:int;comment:文件大小" json:"fileSize"`
	CreateTime time.Time `gorm:"column:create_time;type:int unsigned;not null;autoCreateTime" json:"createTime"`
	UpdateTime time.Time `gorm:"column:update_time;type:int unsigned;not null;autoUpdateTime" json:"updateTime"`
}

// TableName Episode's table name
func (*Episode) TableName() string {
	return TableNameEpisode
}
