// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEpisode = "episode"

// Episode mapped from table <episode>
type Episode struct {
	ID           int64   `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	VideoID      int64   `gorm:"column:video_id;type:bigint;not null;comment:影片id" json:"videoId"`
	Episode      int32   `gorm:"column:episode;type:int;not null;comment:第几集" json:"episode"`
	EpisodeTitle string  `gorm:"column:episode_title;type:varchar(1024);not null;comment:集标题" json:"episodeTitle"`
	URL          *string `gorm:"column:url;type:varchar(1024);comment:影片地址，如果非internal可以为空，每次调用外部数据源接口获取播放地址" json:"url"`
	Platform     *string `gorm:"column:platform;type:varchar(45);comment:internal, xiaoya, aliyun" json:"platform"`
	Ext          *string `gorm:"column:ext;type:varchar(1024);comment:扩展参数" json:"ext"`
	Duration     *int64  `gorm:"column:duration;type:bigint;comment:影片时长，秒" json:"duration"`
	IsValid      bool    `gorm:"column:is_valid;type:tinyint(1);not null;default:1;comment:是否有效" json:"isValid"`
}

// TableName Episode's table name
func (*Episode) TableName() string {
	return TableNameEpisode
}
