// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKeyword = "keyword"

// Keyword 关键词
type Keyword struct {
	ID   uint64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id,string"` // 主键
	Name string `gorm:"column:name;not null;comment:词名称" json:"name"`                        // 词名称
}

// TableName Keyword's table name
func (*Keyword) TableName() string {
	return TableNameKeyword
}
