// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStudio = "studio"

// Studio 出品方
type Studio struct {
	ID      uint64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id,string"` // 主键
	Name    string `gorm:"column:name;not null;comment:名称" json:"name"`                         // 名称
	Country string `gorm:"column:country;not null;comment:国家" json:"country"`                   // 国家
	Logo    string `gorm:"column:logo;comment:logo的地址" json:"logo"`                             // logo的地址
}

// TableName Studio's table name
func (*Studio) TableName() string {
	return TableNameStudio
}
