// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideoStudioMapping = "video_studio_mapping"

// VideoStudioMapping mapped from table <video_studio_mapping>
type VideoStudioMapping struct {
	ID         int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	VideoType  string     `gorm:"column:video_type;type:varchar(32);not null;comment:影片类型，movie,series,season,episode" json:"videoType"`
	VideoID    int64      `gorm:"column:video_id;type:bigint;not null;comment:影片id，根据video_type类型分别来自movie,series,season,episode表" json:"videoId"`
	StudioID   int64      `gorm:"column:studio_id;type:bigint;not null;comment:出品方id" json:"studioId"`
	CreateTime *time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"createTime"`
	UpdateTime *time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"updateTime"`
}

// TableName VideoStudioMapping's table name
func (*VideoStudioMapping) TableName() string {
	return TableNameVideoStudioMapping
}
