// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideoActorMapping = "video_actor_mapping"

// VideoActorMapping mapped from table <video_actor_mapping>
type VideoActorMapping struct {
	ID         int64   `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	VideoID    int64   `gorm:"column:video_id;type:bigint;not null;comment:影片id" json:"videoId"`
	ActorID    int64   `gorm:"column:actor_id;type:bigint;not null;comment:演职人员id" json:"actorId"`
	Character  *string `gorm:"column:character;type:varchar(128);comment:饰演角色名称" json:"character"`
	IsDirector bool    `gorm:"column:is_director;type:tinyint(1);not null;comment:是否导演" json:"isDirector"`
}

// TableName VideoActorMapping's table name
func (*VideoActorMapping) TableName() string {
	return TableNameVideoActorMapping
}
