// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "video"

// Video mapped from table <video>
type Video struct {
	ID                 int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	Title              string    `gorm:"column:title;type:varchar(1024);not null;comment:标题" json:"title"`
	VideoType          string    `gorm:"column:video_type;type:varchar(32);not null;comment:影片类型，movie,tvSeries,tvShows,cartoon,record" json:"videoType"`
	VoteRate           *float32  `gorm:"column:vote_rate;type:float;comment:评分" json:"voteRate"`
	Region             *string   `gorm:"column:region;type:varchar(32);comment:国家" json:"region"`
	TotalEpisode       *int32    `gorm:"column:total_episode;type:int;comment:总集数，减去episode的集数判断是否完结" json:"totalEpisode"`
	Description        *string   `gorm:"column:description;type:varchar(1024);comment:简介" json:"description"`
	Ext                *string   `gorm:"column:ext;type:varchar(1024);comment:扩展参数" json:"ext"`
	PublishDay         *string   `gorm:"column:publish_day;type:varchar(32);comment:出版月份，yyyymmdd" json:"publishDay"`
	Thumbnail          *string   `gorm:"column:thumbnail;type:varchar(2048);comment:缩略图" json:"thumbnail"`
	Genres             *string   `gorm:"column:genres;type:varchar(2048);comment:流派，固定枚举，多个时用,分隔" json:"genres"`
	CreateTime         time.Time `gorm:"column:create_time;type:int unsigned;not null;autoCreateTime;comment:创建时间" json:"createTime"`
	UpdateTime         time.Time `gorm:"column:update_time;type:int unsigned;not null;autoUpdateTime;comment:更新时间" json:"updateTime"`
	IsValid            bool      `gorm:"column:is_valid;type:tinyint(1);not null;default:1;comment:是否有效" json:"isValid"`
	JellyfinID         string    `gorm:"column:jellyfin_id;type:varchar(255);not null;comment:jellyfin的id" json:"jellyfinId"`
	JellyfinCreateTime time.Time `gorm:"column:jellyfin_create_time;type:datetime;not null;comment:jellyfin创建时间" json:"jellyfinCreateTime"`
	WatchCount         int64     `gorm:"column:watch_count;type:bigint unsigned;not null;comment:观看次数" json:"watchCount"`
	Ratio              *string   `gorm:"column:ratio;type:varchar(255);comment:分辨率LD，SD，HD，QHD" json:"ratio"`
	JellyfinRootPathID *string   `gorm:"column:jellyfin_root_path_id;type:varchar(255)" json:"jellyfinRootPathId"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
