// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideoSubtitleMapping = "video_subtitle_mapping"

// VideoSubtitleMapping mapped from table <video_subtitle_mapping>
type VideoSubtitleMapping struct {
	ID        int64  `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	VideoType string `gorm:"column:video_type;type:varchar(32);not null;comment:影片类型，movie,series,season,episode" json:"videoType"`
	VideoID   int64  `gorm:"column:video_id;type:bigint;not null;comment:影片id，根据video_type类型分别来自movie,series,season,episode表" json:"videoId"`
	URL       string `gorm:"column:url;type:varchar(1024);not null;comment:字幕地址" json:"url"`
	Title     string `gorm:"column:title;type:varchar(1024);not null;comment:字幕标题" json:"title"`
	Language  string `gorm:"column:language;type:varchar(32);not null;comment:字幕语言" json:"language"`
	MimeType  string `gorm:"column:mime_type;type:varchar(256);not null;comment:字幕格式" json:"mimeType"`
}

// TableName VideoSubtitleMapping's table name
func (*VideoSubtitleMapping) TableName() string {
	return TableNameVideoSubtitleMapping
}
