// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideoUserMapping = "video_user_mapping"

// VideoUserMapping mapped from table <video_user_mapping>
type VideoUserMapping struct {
	ID                  int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`
	VideoID             int64      `gorm:"column:video_id;type:bigint;not null;comment:影片id" json:"videoId"`
	LastPlayedPosition  *int64     `gorm:"column:last_played_position;type:bigint;comment:影片上次播放位置，第n秒" json:"lastPlayedPosition"`
	LastPlayedTime      *time.Time `gorm:"column:last_played_time;type:datetime;comment:上次点击播放时间" json:"lastPlayedTime"`
	LastPlayedEpisodeID *int64     `gorm:"column:last_played_episode_id;type:bigint;comment:上次点击播放集id" json:"lastPlayedEpisodeId"`
	IsFavorite          bool       `gorm:"column:is_favorite;type:tinyint(1);not null;comment:是否收藏喜欢" json:"isFavorite"`
	UserID              int64      `gorm:"column:user_id;type:bigint;not null;comment:用户id" json:"userId"`
	CreateTime          time.Time  `gorm:"column:create_time;type:int unsigned;not null;autoCreateTime;comment:创建时间" json:"createTime"`
	UpdateTime          time.Time  `gorm:"column:update_time;type:int unsigned;not null;autoUpdateTime;comment:更新时间" json:"updateTime"`
}

// TableName VideoUserMapping's table name
func (*VideoUserMapping) TableName() string {
	return TableNameVideoUserMapping
}
