// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.1
// - protoc             v5.29.3
// source: proto/appversion.proto

package appversion

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAppVersionRemoteServiceGetLastVersion = "/gnboot.AppVersionRemoteService/GetLastVersion"

type AppVersionRemoteServiceHTTPServer interface {
	GetLastVersion(context.Context, *GetLastAppVersionRequest) (*AppVersion, error)
}

func RegisterAppVersionRemoteServiceHTTPServer(s *http.Server, srv AppVersionRemoteServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/version/getLastVersion", _AppVersionRemoteService_GetLastVersion0_HTTP_Handler(srv))
}

func _AppVersionRemoteService_GetLastVersion0_HTTP_Handler(srv AppVersionRemoteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLastAppVersionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAppVersionRemoteServiceGetLastVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLastVersion(ctx, req.(*GetLastAppVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AppVersion)
		return ctx.Result(200, reply)
	}
}

type AppVersionRemoteServiceHTTPClient interface {
	GetLastVersion(ctx context.Context, req *GetLastAppVersionRequest, opts ...http.CallOption) (rsp *AppVersion, err error)
}

type AppVersionRemoteServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAppVersionRemoteServiceHTTPClient(client *http.Client) AppVersionRemoteServiceHTTPClient {
	return &AppVersionRemoteServiceHTTPClientImpl{client}
}

func (c *AppVersionRemoteServiceHTTPClientImpl) GetLastVersion(ctx context.Context, in *GetLastAppVersionRequest, opts ...http.CallOption) (*AppVersion, error) {
	var out AppVersion
	pattern := "/version/getLastVersion"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAppVersionRemoteServiceGetLastVersion))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
