# staging
system:
  url-prefix: stage-api
  port: 9090
  pprof-port: 9005

mysql:
  uri: 'root:root@tcp(127.0.0.1:3306)/gin_web_stage?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
