version: '3'

services:
  mysql-gntv:
    image: mysql
    hostname: gndb
    container_name: gndb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=gnvideo
    volumes:
      - ./data/mysql/user:/var/lib/mysql
      - ./conf/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - shared_net

  cache-redis:
    image: redis
    hostname: cache-redis
    volumes:
      - ./data/redis/cache/:/data
      - ./conf/redis/cache/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    command: ["redis-server","/etc/redis/redis.conf"]
    restart: always
    networks:
      - shared_net

  nacos:
    image: nacos/nacos-server:v2.0.3
    container_name: nacos-server
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - 8848:8848
      - 9848:9848
    volumes:
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    restart: always
    networks:
      - shared_net

  xiaoya:
    image: xiaoyaliu/alist:latest
    container_name: xiaoya
    restart: unless-stopped
    ports:
      - "8765:80"
    volumes:
      - /Users/wing/Documents/alist/data:/data
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - shared_net

  emby:
    image: emby/embyserver_arm64v8:latest
    container_name: emby-server-compose
    ports:
      - "8096:8096"
    volumes:
      - /Users/wing/Documents/xiaoya_emby/config:/config
      - /Users/wing/Documents/alist/config/nsswitch.conf:/etc/nsswitch.conf
      - /Users/wing/Documents/xiaoya_emby/xiaoya:/media
    restart: always
    privileged: true
    security_opt:
      - seccomp:unconfined
    networks:
      - shared_net

  gnboot:
    image: dabache/gnboot:latest
    container_name: gnboot
    ports:
      - 8180:8180
      - 8080:8080
    restart: always
    networks:
      - shared_net

networks:
  shared_net:
    driver: bridge
