version: '3'

services:
  Mysql:
    image: mysql
    hostname: Mysql
    container_name: Mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_HOST=%
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=video_user
      - MYSQL_PASSWORD=SecurePass123!
      - MYSQL_DATABASE=gnvideo
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf/mysql/conf.d:/etc/mysql/conf.d
    restart: always
    networks:
      - shared_net

  Redis:
    image: redis
    hostname: Redis
    container_name: Redis
    volumes:
      - ./data/redis/cache/:/data
      - ./conf/redis/cache/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    command: ["redis-server", "/etc/redis/redis.conf"]
    restart: always
    networks:
      - shared_net

  Nacos:
    image: nacos/nacos-server:v2.3.1-slim
    hostname: Nacos
    container_name: Nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - 8848:8848
      - 9848:9848
    volumes:
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    restart: always
    networks:
      - shared_net

  Xiaoya:
    image: xiaoyaliu/alist:latest
    container_name: Xiaoya
    ports:
      - "8765:80"
    volumes:
      - /Users/wing/Documents/alist/data:/data
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - shared_net

  Emby:
    image: emby/embyserver_arm64v8:latest
    container_name: Emby
    ports:
      - "8096:8096"
    volumes:
      - /Users/wing/Documents/xiaoya_emby/config:/config
      - /Users/wing/Documents/alist/config/nsswitch.conf:/etc/nsswitch.conf
      - /Users/wing/Documents/xiaoya_emby/xiaoya:/media
    restart: always
    privileged: true
    security_opt:
      - seccomp:unconfined
    networks:
      - shared_net

  Gnboot:
    image: dabache/gnboot:latest
    container_name: Gnboot
    hostname: Gnboot
    environment:
      - APP_ENV=prod
    ports:
      - 8888:8888
      - 9999:9999
    restart: always
    networks:
      - shared_net

networks:
  shared_net:
    driver: bridge
