// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/subtitle.proto

package subtitle

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SubtitleResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// gerror encountered is returned, or nil if there are no violations.
func (m *SubtitleResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubtitleResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SubtitleRespMultiError, or
// nil if none found.
func (m *SubtitleResp) ValidateAll() error {
	return m.validate(true)
}

func (m *SubtitleResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Url

	// no validation rules for Title

	// no validation rules for Language

	// no validation rules for MimeType

	if len(errors) > 0 {
		return SubtitleRespMultiError(errors)
	}

	return nil
}

// SubtitleRespMultiError is an gerror wrapping multiple validation errors
// returned by SubtitleResp.ValidateAll() if the designated constraints aren't met.
type SubtitleRespMultiError []error

// Error returns a concatenation of all the gerror messages it wraps.
func (m SubtitleRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubtitleRespMultiError) AllErrors() []error { return m }

// SubtitleRespValidationError is the validation gerror returned by
// SubtitleResp.Validate if the designated constraints aren't met.
type SubtitleRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubtitleRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubtitleRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubtitleRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubtitleRespValidationError) Key() bool { return e.key }

// ErrorName returns gerror name.
func (e SubtitleRespValidationError) ErrorName() string { return "SubtitleRespValidationError" }

// Error satisfies the builtin gerror interface
func (e SubtitleRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubtitleResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubtitleRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubtitleRespValidationError{}

// Validate checks the field values on FindSubtitleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first gerror encountered is returned, or nil if there are no violations.
func (m *FindSubtitleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FindSubtitleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FindSubtitleRequestMultiError, or nil if none found.
func (m *FindSubtitleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *FindSubtitleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FindSubtitleRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FindSubtitleRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FindSubtitleRequestValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FindSubtitleRequestMultiError(errors)
	}

	return nil
}

// FindSubtitleRequestMultiError is an gerror wrapping multiple validation
// errors returned by FindSubtitleRequest.ValidateAll() if the designated
// constraints aren't met.
type FindSubtitleRequestMultiError []error

// Error returns a concatenation of all the gerror messages it wraps.
func (m FindSubtitleRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FindSubtitleRequestMultiError) AllErrors() []error { return m }

// FindSubtitleRequestValidationError is the validation gerror returned by
// FindSubtitleRequest.Validate if the designated constraints aren't met.
type FindSubtitleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FindSubtitleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FindSubtitleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FindSubtitleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FindSubtitleRequestValidationError) Key() bool { return e.key }

// ErrorName returns gerror name.
func (e FindSubtitleRequestValidationError) ErrorName() string {
	return "FindSubtitleRequestValidationError"
}

// Error satisfies the builtin gerror interface
func (e FindSubtitleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFindSubtitleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FindSubtitleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FindSubtitleRequestValidationError{}

// Validate checks the field values on FindSubtitleResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first gerror encountered is returned, or nil if there are no violations.
func (m *FindSubtitleResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FindSubtitleResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FindSubtitleRespMultiError, or nil if none found.
func (m *FindSubtitleResp) ValidateAll() error {
	return m.validate(true)
}

func (m *FindSubtitleResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, FindSubtitleRespValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, FindSubtitleRespValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return FindSubtitleRespValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return FindSubtitleRespMultiError(errors)
	}

	return nil
}

// FindSubtitleRespMultiError is an gerror wrapping multiple validation errors
// returned by FindSubtitleResp.ValidateAll() if the designated constraints
// aren't met.
type FindSubtitleRespMultiError []error

// Error returns a concatenation of all the gerror messages it wraps.
func (m FindSubtitleRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FindSubtitleRespMultiError) AllErrors() []error { return m }

// FindSubtitleRespValidationError is the validation gerror returned by
// FindSubtitleResp.Validate if the designated constraints aren't met.
type FindSubtitleRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FindSubtitleRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FindSubtitleRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FindSubtitleRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FindSubtitleRespValidationError) Key() bool { return e.key }

// ErrorName returns gerror name.
func (e FindSubtitleRespValidationError) ErrorName() string { return "FindSubtitleRespValidationError" }

// Error satisfies the builtin gerror interface
func (e FindSubtitleRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFindSubtitleResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FindSubtitleRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FindSubtitleRespValidationError{}
