server:
  prod: false
  machineId: ''
  http:
    addr: 0.0.0.0:8080
    timeout: 20s
  grpc:
    addr: 0.0.0.0:8180
    timeout: 20s
  language: 'en'
  idempotent: true
  validate: true
  # disable biz.Cache or not
  nocache: true
data:
  database:
    driver: mysql
    # dsn: 'root:root@sily(127.0.0.1:3306)/gnboot?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
    dsn: ''
    endpoint: '127.0.0.1:3306'
    username: 'root'
    password: 'sily'
    schema: 'video'
    query: 'charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
#    tenants:
#      gnboot.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/gnboot?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms}'
#      gnboot2.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/gnboot2?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
#      gnboot3.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/gnboot3?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
#      gnboot4.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/gnboot4?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  redis:
    # redis dsn like this:
    # redis://[:password@]host[:port][/dbnumber]
    # redis://[:password@]host1[:port][,host2:[:port]][,hostN:[:port]][?master=masterName&sentinel=true]
    dsn: 'redis://127.0.0.1:6379/0'
