xiaoya_url: "http://127.0.0.1:5678"
server:
  prod: false
  machineId: ''
  http:
    addr: 0.0.0.0:8080
    timeout: 20s
  grpc:
    addr: 0.0.0.0:8180
    timeout: 20s
  language: 'en'
  idempotent: true
  validate: true
  # disable service.Cache or not
  nocache: true
  # disable service.Trace or not
data:
  database:
    driver: mysql
    # dsn: 'root:root@tcp(127.0.0.1:3306)/gnboot?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
    dsn: ''
    endpoint: 'mysql.sqlpub.com:3306'
    username: 'gnvideo'
    password: '7H5rdOAIMA815pXz'
    schema: 'gnvideo'
    query: 'charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
#    tenants:
#      gnboot.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/gnboot?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms}'
#      gnboot2.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/gnboot2?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
#      gnboot3.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/gnboot3?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
#      gnboot4.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/gnboot4?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  redis:
    dsn: 'redis://127.0.0.1:6379/0'
