# go install github.com/go-cinch/cinch/cmd/cinch@latest
# cinch gen gorm
gen:
  dsn: 'root:123456@tcp(localhost:3306)/video?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  tables:
  - actor
  - app_version
  - episode
  - genre
  - keyword
  - movie
  - season
  - series
  - studio
  - user
  - video_actor_mapping
  - video_genre_mapping
  - video_keyword_mapping
  - video_studio_mapping
  - video_subtitle_mapping
  - video_user_mapping
  exclude:
  - schema_migrations
  association:
  field-with-string-tag:
