task:
  taskUserPackageCheck:
    name: '每10分钟执行'
    expr: '*/10 * * * * '
    
  xiaoya_get_video:
    name: 'xiaoya_get_video'
    expr: '*/5 * * * *'  # 每5分钟执行

#    *　　*　　*　　*　　*　　
#    分　 时　 日　 月　 周