// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gen/helper"

	"gorm.io/plugin/dbresolver"

	"gnboot/internal/data/model"
)

func newVideoSubtitleMapping(db *gorm.DB, opts ...gen.DOOption) videoSubtitleMapping {
	_videoSubtitleMapping := videoSubtitleMapping{}

	_videoSubtitleMapping.videoSubtitleMappingDo.UseDB(db, opts...)
	_videoSubtitleMapping.videoSubtitleMappingDo.UseModel(&model.VideoSubtitleMapping{})

	tableName := _videoSubtitleMapping.videoSubtitleMappingDo.TableName()
	_videoSubtitleMapping.ALL = field.NewAsterisk(tableName)
	_videoSubtitleMapping.ID = field.NewUint64(tableName, "id")
	_videoSubtitleMapping.VideoType = field.NewString(tableName, "video_type")
	_videoSubtitleMapping.VideoID = field.NewInt64(tableName, "video_id")
	_videoSubtitleMapping.URL = field.NewString(tableName, "url")
	_videoSubtitleMapping.Title = field.NewString(tableName, "title")
	_videoSubtitleMapping.Language = field.NewString(tableName, "language")
	_videoSubtitleMapping.MimeType = field.NewString(tableName, "mime_type")

	_videoSubtitleMapping.fillFieldMap()

	return _videoSubtitleMapping
}

// videoSubtitleMapping 影片字幕关联表
type videoSubtitleMapping struct {
	videoSubtitleMappingDo videoSubtitleMappingDo

	ALL       field.Asterisk
	ID        field.Uint64 // 主键
	VideoType field.String // 影片类型，movie,series,season,episode
	VideoID   field.Int64  // 影片id，根据video_type类型分别来自movie,series,season,episode表
	URL       field.String // 字幕地址
	Title     field.String // 字幕标题
	Language  field.String // 字幕语言
	MimeType  field.String // 字幕格式

	fieldMap map[string]field.Expr
}

func (v videoSubtitleMapping) Table(newTableName string) *videoSubtitleMapping {
	v.videoSubtitleMappingDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v videoSubtitleMapping) As(alias string) *videoSubtitleMapping {
	v.videoSubtitleMappingDo.DO = *(v.videoSubtitleMappingDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *videoSubtitleMapping) updateTableName(table string) *videoSubtitleMapping {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewUint64(table, "id")
	v.VideoType = field.NewString(table, "video_type")
	v.VideoID = field.NewInt64(table, "video_id")
	v.URL = field.NewString(table, "url")
	v.Title = field.NewString(table, "title")
	v.Language = field.NewString(table, "language")
	v.MimeType = field.NewString(table, "mime_type")

	v.fillFieldMap()

	return v
}

func (v *videoSubtitleMapping) WithContext(ctx context.Context) *videoSubtitleMappingDo {
	return v.videoSubtitleMappingDo.WithContext(ctx)
}

func (v videoSubtitleMapping) TableName() string { return v.videoSubtitleMappingDo.TableName() }

func (v videoSubtitleMapping) Alias() string { return v.videoSubtitleMappingDo.Alias() }

func (v videoSubtitleMapping) Columns(cols ...field.Expr) gen.Columns {
	return v.videoSubtitleMappingDo.Columns(cols...)
}

func (v *videoSubtitleMapping) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *videoSubtitleMapping) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 7)
	v.fieldMap["id"] = v.ID
	v.fieldMap["video_type"] = v.VideoType
	v.fieldMap["video_id"] = v.VideoID
	v.fieldMap["url"] = v.URL
	v.fieldMap["title"] = v.Title
	v.fieldMap["language"] = v.Language
	v.fieldMap["mime_type"] = v.MimeType
}

func (v videoSubtitleMapping) clone(db *gorm.DB) videoSubtitleMapping {
	v.videoSubtitleMappingDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v videoSubtitleMapping) replaceDB(db *gorm.DB) videoSubtitleMapping {
	v.videoSubtitleMappingDo.ReplaceDB(db)
	return v
}

type videoSubtitleMappingDo struct{ gen.DO }

// SELECT * FROM `@@table` WHERE `id` = @id LIMIT 1
func (v videoSubtitleMappingDo) GetByID(id uint64) (result model.VideoSubtitleMapping) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM `video_subtitle_mapping` WHERE `id` = ? LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = v.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// SELECT * FROM `@@table`
// {{where}}
//
//	{{if val != ""}}
//	  {{if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%")}}
//	    @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val), '%')
//	  {{else if strings.HasPrefix(val, "%")}}
//	    @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val))
//	  {{else if strings.HasSuffix(val, "%")}}
//	    @@col LIKE CONCAT(TRIM(BOTH '%' FROM @val), '%')
//	  {{else}}
//	    @@col = @val
//	  {{end}}
//	{{end}}
//
// {{end}}
// LIMIT 1
func (v videoSubtitleMappingDo) GetByCol(col string, val string) (result model.VideoSubtitleMapping) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM `video_subtitle_mapping` ")
	var whereSQL0 strings.Builder
	if val != "" {
		if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?), '%') ")
		} else if strings.HasPrefix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?)) ")
		} else if strings.HasSuffix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT(TRIM(BOTH '%' FROM ?), '%') ")
		} else {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " = ? ")
		}
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)
	generateSQL.WriteString("LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = v.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// SELECT * FROM `@@table`
// {{if len(cols) == len(vals)}}
// {{where}}
//
//	  {{for i, col := range cols}}
//	    {{for j, val := range vals}}
//	      {{if i == j}}
//	        {{if val != ""}}
//	          {{if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%")}}
//	            @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val), '%') AND
//	          {{else if strings.HasPrefix(val, "%")}}
//	            @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val)) AND
//	          {{else if strings.HasSuffix(val, "%")}}
//	            @@col LIKE CONCAT(TRIM(BOTH '%' FROM @val), '%') AND
//	          {{else}}
//	            @@col = @val AND
//	          {{end}}
//	        {{end}}
//	      {{end}}
//	    {{end}}
//	  {{end}}
//	{{end}}
//
// {{end}}
// LIMIT 1
func (v videoSubtitleMappingDo) GetByCols(cols []string, vals []string) (result model.VideoSubtitleMapping) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM `video_subtitle_mapping` ")
	if len(cols) == len(vals) {
		var whereSQL0 strings.Builder
		for i, col := range cols {
			for j, val := range vals {
				if i == j {
					if val != "" {
						if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?), '%') AND ")
						} else if strings.HasPrefix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?)) AND ")
						} else if strings.HasSuffix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT(TRIM(BOTH '%' FROM ?), '%') AND ")
						} else {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " = ? AND ")
						}
					}
				}
			}
		}
		helper.JoinWhereBuilder(&generateSQL, whereSQL0)
	}
	generateSQL.WriteString("LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = v.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// SELECT * FROM `@@table`
// {{where}}
//
//	{{if val != ""}}
//	  {{if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%")}}
//	    @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val), '%')
//	  {{else if strings.HasPrefix(val, "%")}}
//	    @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val))
//	  {{else if strings.HasSuffix(val, "%")}}
//	    @@col LIKE CONCAT(TRIM(BOTH '%' FROM @val), '%')
//	  {{else}}
//	    @@col = @val
//	  {{end}}
//	{{end}}
//
// {{end}}
func (v videoSubtitleMappingDo) FindByCol(col string, val string) (result []model.VideoSubtitleMapping) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM `video_subtitle_mapping` ")
	var whereSQL0 strings.Builder
	if val != "" {
		if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?), '%') ")
		} else if strings.HasPrefix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?)) ")
		} else if strings.HasSuffix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT(TRIM(BOTH '%' FROM ?), '%') ")
		} else {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " = ? ")
		}
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = v.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// SELECT * FROM `@@table`
// {{if len(cols) == len(vals)}}
// {{where}}
//
//	  {{for i, col := range cols}}
//	    {{for j, val := range vals}}
//	      {{if i == j}}
//	        {{if val != ""}}
//	          {{if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%")}}
//	            @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val), '%') AND
//	          {{else if strings.HasPrefix(val, "%")}}
//	            @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val)) AND
//	          {{else if strings.HasSuffix(val, "%")}}
//	            @@col LIKE CONCAT(TRIM(BOTH '%' FROM @val), '%') AND
//	          {{else}}
//	            @@col = @val AND
//	          {{end}}
//	        {{end}}
//	      {{end}}
//	    {{end}}
//	  {{end}}
//	{{end}}
//
// {{end}}
func (v videoSubtitleMappingDo) FindByCols(cols []string, vals []string) (result []model.VideoSubtitleMapping) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM `video_subtitle_mapping` ")
	if len(cols) == len(vals) {
		var whereSQL0 strings.Builder
		for i, col := range cols {
			for j, val := range vals {
				if i == j {
					if val != "" {
						if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?), '%') AND ")
						} else if strings.HasPrefix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?)) AND ")
						} else if strings.HasSuffix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT(TRIM(BOTH '%' FROM ?), '%') AND ")
						} else {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " = ? AND ")
						}
					}
				}
			}
		}
		helper.JoinWhereBuilder(&generateSQL, whereSQL0)
	}

	var executeSQL *gorm.DB
	executeSQL = v.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

func (v videoSubtitleMappingDo) Debug() *videoSubtitleMappingDo {
	return v.withDO(v.DO.Debug())
}

func (v videoSubtitleMappingDo) WithContext(ctx context.Context) *videoSubtitleMappingDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v videoSubtitleMappingDo) ReadDB() *videoSubtitleMappingDo {
	return v.Clauses(dbresolver.Read)
}

func (v videoSubtitleMappingDo) WriteDB() *videoSubtitleMappingDo {
	return v.Clauses(dbresolver.Write)
}

func (v videoSubtitleMappingDo) Session(config *gorm.Session) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Session(config))
}

func (v videoSubtitleMappingDo) Clauses(conds ...clause.Expression) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v videoSubtitleMappingDo) Returning(value interface{}, columns ...string) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v videoSubtitleMappingDo) Not(conds ...gen.Condition) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v videoSubtitleMappingDo) Or(conds ...gen.Condition) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v videoSubtitleMappingDo) Select(conds ...field.Expr) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v videoSubtitleMappingDo) Where(conds ...gen.Condition) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v videoSubtitleMappingDo) Order(conds ...field.Expr) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v videoSubtitleMappingDo) Distinct(cols ...field.Expr) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v videoSubtitleMappingDo) Omit(cols ...field.Expr) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v videoSubtitleMappingDo) Join(table schema.Tabler, on ...field.Expr) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v videoSubtitleMappingDo) LeftJoin(table schema.Tabler, on ...field.Expr) *videoSubtitleMappingDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v videoSubtitleMappingDo) RightJoin(table schema.Tabler, on ...field.Expr) *videoSubtitleMappingDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v videoSubtitleMappingDo) Group(cols ...field.Expr) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v videoSubtitleMappingDo) Having(conds ...gen.Condition) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v videoSubtitleMappingDo) Limit(limit int) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v videoSubtitleMappingDo) Offset(offset int) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v videoSubtitleMappingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v videoSubtitleMappingDo) Unscoped() *videoSubtitleMappingDo {
	return v.withDO(v.DO.Unscoped())
}

func (v videoSubtitleMappingDo) Create(values ...*model.VideoSubtitleMapping) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v videoSubtitleMappingDo) CreateInBatches(values []*model.VideoSubtitleMapping, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v videoSubtitleMappingDo) Save(values ...*model.VideoSubtitleMapping) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v videoSubtitleMappingDo) First() (*model.VideoSubtitleMapping, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoSubtitleMapping), nil
	}
}

func (v videoSubtitleMappingDo) Take() (*model.VideoSubtitleMapping, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoSubtitleMapping), nil
	}
}

func (v videoSubtitleMappingDo) Last() (*model.VideoSubtitleMapping, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoSubtitleMapping), nil
	}
}

func (v videoSubtitleMappingDo) Find() ([]*model.VideoSubtitleMapping, error) {
	result, err := v.DO.Find()
	return result.([]*model.VideoSubtitleMapping), err
}

func (v videoSubtitleMappingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VideoSubtitleMapping, err error) {
	buf := make([]*model.VideoSubtitleMapping, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v videoSubtitleMappingDo) FindInBatches(result *[]*model.VideoSubtitleMapping, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v videoSubtitleMappingDo) Attrs(attrs ...field.AssignExpr) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v videoSubtitleMappingDo) Assign(attrs ...field.AssignExpr) *videoSubtitleMappingDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v videoSubtitleMappingDo) Joins(fields ...field.RelationField) *videoSubtitleMappingDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v videoSubtitleMappingDo) Preload(fields ...field.RelationField) *videoSubtitleMappingDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v videoSubtitleMappingDo) FirstOrInit() (*model.VideoSubtitleMapping, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoSubtitleMapping), nil
	}
}

func (v videoSubtitleMappingDo) FirstOrCreate() (*model.VideoSubtitleMapping, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoSubtitleMapping), nil
	}
}

func (v videoSubtitleMappingDo) FindByPage(offset int, limit int) (result []*model.VideoSubtitleMapping, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v videoSubtitleMappingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v videoSubtitleMappingDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v videoSubtitleMappingDo) Delete(models ...*model.VideoSubtitleMapping) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *videoSubtitleMappingDo) withDO(do gen.Dao) *videoSubtitleMappingDo {
	v.DO = *do.(*gen.DO)
	return v
}
