// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gen/helper"

	"gorm.io/plugin/dbresolver"

	"gnboot/internal/data/model"
)

func newVideoStudioMapping(db *gorm.DB, opts ...gen.DOOption) videoStudioMapping {
	_videoStudioMapping := videoStudioMapping{}

	_videoStudioMapping.videoStudioMappingDo.UseDB(db, opts...)
	_videoStudioMapping.videoStudioMappingDo.UseModel(&model.VideoStudioMapping{})

	tableName := _videoStudioMapping.videoStudioMappingDo.TableName()
	_videoStudioMapping.ALL = field.NewAsterisk(tableName)
	_videoStudioMapping.ID = field.NewUint64(tableName, "id")
	_videoStudioMapping.VideoType = field.NewString(tableName, "video_type")
	_videoStudioMapping.VideoID = field.NewInt64(tableName, "video_id")
	_videoStudioMapping.StudioID = field.NewInt64(tableName, "studio_id")

	_videoStudioMapping.fillFieldMap()

	return _videoStudioMapping
}

// videoStudioMapping 影片出品方关联表
type videoStudioMapping struct {
	videoStudioMappingDo videoStudioMappingDo

	ALL       field.Asterisk
	ID        field.Uint64 // 主键
	VideoType field.String // 影片类型，movie,series,season,episode
	VideoID   field.Int64  // 影片id，根据video_type类型分别来自movie,series,season,episode表
	StudioID  field.Int64  // 出品方id

	fieldMap map[string]field.Expr
}

func (v videoStudioMapping) Table(newTableName string) *videoStudioMapping {
	v.videoStudioMappingDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v videoStudioMapping) As(alias string) *videoStudioMapping {
	v.videoStudioMappingDo.DO = *(v.videoStudioMappingDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *videoStudioMapping) updateTableName(table string) *videoStudioMapping {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewUint64(table, "id")
	v.VideoType = field.NewString(table, "video_type")
	v.VideoID = field.NewInt64(table, "video_id")
	v.StudioID = field.NewInt64(table, "studio_id")

	v.fillFieldMap()

	return v
}

func (v *videoStudioMapping) WithContext(ctx context.Context) *videoStudioMappingDo {
	return v.videoStudioMappingDo.WithContext(ctx)
}

func (v videoStudioMapping) TableName() string { return v.videoStudioMappingDo.TableName() }

func (v videoStudioMapping) Alias() string { return v.videoStudioMappingDo.Alias() }

func (v videoStudioMapping) Columns(cols ...field.Expr) gen.Columns {
	return v.videoStudioMappingDo.Columns(cols...)
}

func (v *videoStudioMapping) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *videoStudioMapping) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 4)
	v.fieldMap["id"] = v.ID
	v.fieldMap["video_type"] = v.VideoType
	v.fieldMap["video_id"] = v.VideoID
	v.fieldMap["studio_id"] = v.StudioID
}

func (v videoStudioMapping) clone(db *gorm.DB) videoStudioMapping {
	v.videoStudioMappingDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v videoStudioMapping) replaceDB(db *gorm.DB) videoStudioMapping {
	v.videoStudioMappingDo.ReplaceDB(db)
	return v
}

type videoStudioMappingDo struct{ gen.DO }

// SELECT * FROM `@@table` WHERE `id` = @id LIMIT 1
func (v videoStudioMappingDo) GetByID(id uint64) (result model.VideoStudioMapping) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM `video_studio_mapping` WHERE `id` = ? LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = v.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// SELECT * FROM `@@table`
// {{where}}
//
//	{{if val != ""}}
//	  {{if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%")}}
//	    @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val), '%')
//	  {{else if strings.HasPrefix(val, "%")}}
//	    @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val))
//	  {{else if strings.HasSuffix(val, "%")}}
//	    @@col LIKE CONCAT(TRIM(BOTH '%' FROM @val), '%')
//	  {{else}}
//	    @@col = @val
//	  {{end}}
//	{{end}}
//
// {{end}}
// LIMIT 1
func (v videoStudioMappingDo) GetByCol(col string, val string) (result model.VideoStudioMapping) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM `video_studio_mapping` ")
	var whereSQL0 strings.Builder
	if val != "" {
		if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?), '%') ")
		} else if strings.HasPrefix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?)) ")
		} else if strings.HasSuffix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT(TRIM(BOTH '%' FROM ?), '%') ")
		} else {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " = ? ")
		}
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)
	generateSQL.WriteString("LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = v.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// SELECT * FROM `@@table`
// {{if len(cols) == len(vals)}}
// {{where}}
//
//	  {{for i, col := range cols}}
//	    {{for j, val := range vals}}
//	      {{if i == j}}
//	        {{if val != ""}}
//	          {{if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%")}}
//	            @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val), '%') AND
//	          {{else if strings.HasPrefix(val, "%")}}
//	            @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val)) AND
//	          {{else if strings.HasSuffix(val, "%")}}
//	            @@col LIKE CONCAT(TRIM(BOTH '%' FROM @val), '%') AND
//	          {{else}}
//	            @@col = @val AND
//	          {{end}}
//	        {{end}}
//	      {{end}}
//	    {{end}}
//	  {{end}}
//	{{end}}
//
// {{end}}
// LIMIT 1
func (v videoStudioMappingDo) GetByCols(cols []string, vals []string) (result model.VideoStudioMapping) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM `video_studio_mapping` ")
	if len(cols) == len(vals) {
		var whereSQL0 strings.Builder
		for i, col := range cols {
			for j, val := range vals {
				if i == j {
					if val != "" {
						if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?), '%') AND ")
						} else if strings.HasPrefix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?)) AND ")
						} else if strings.HasSuffix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT(TRIM(BOTH '%' FROM ?), '%') AND ")
						} else {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " = ? AND ")
						}
					}
				}
			}
		}
		helper.JoinWhereBuilder(&generateSQL, whereSQL0)
	}
	generateSQL.WriteString("LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = v.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// SELECT * FROM `@@table`
// {{where}}
//
//	{{if val != ""}}
//	  {{if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%")}}
//	    @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val), '%')
//	  {{else if strings.HasPrefix(val, "%")}}
//	    @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val))
//	  {{else if strings.HasSuffix(val, "%")}}
//	    @@col LIKE CONCAT(TRIM(BOTH '%' FROM @val), '%')
//	  {{else}}
//	    @@col = @val
//	  {{end}}
//	{{end}}
//
// {{end}}
func (v videoStudioMappingDo) FindByCol(col string, val string) (result []model.VideoStudioMapping) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM `video_studio_mapping` ")
	var whereSQL0 strings.Builder
	if val != "" {
		if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?), '%') ")
		} else if strings.HasPrefix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?)) ")
		} else if strings.HasSuffix(val, "%") {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT(TRIM(BOTH '%' FROM ?), '%') ")
		} else {
			params = append(params, val)
			whereSQL0.WriteString(v.Quote(col) + " = ? ")
		}
	}
	helper.JoinWhereBuilder(&generateSQL, whereSQL0)

	var executeSQL *gorm.DB
	executeSQL = v.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

// SELECT * FROM `@@table`
// {{if len(cols) == len(vals)}}
// {{where}}
//
//	  {{for i, col := range cols}}
//	    {{for j, val := range vals}}
//	      {{if i == j}}
//	        {{if val != ""}}
//	          {{if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%")}}
//	            @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val), '%') AND
//	          {{else if strings.HasPrefix(val, "%")}}
//	            @@col LIKE CONCAT('%', TRIM(BOTH '%' FROM @val)) AND
//	          {{else if strings.HasSuffix(val, "%")}}
//	            @@col LIKE CONCAT(TRIM(BOTH '%' FROM @val), '%') AND
//	          {{else}}
//	            @@col = @val AND
//	          {{end}}
//	        {{end}}
//	      {{end}}
//	    {{end}}
//	  {{end}}
//	{{end}}
//
// {{end}}
func (v videoStudioMappingDo) FindByCols(cols []string, vals []string) (result []model.VideoStudioMapping) {
	var params []interface{}

	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM `video_studio_mapping` ")
	if len(cols) == len(vals) {
		var whereSQL0 strings.Builder
		for i, col := range cols {
			for j, val := range vals {
				if i == j {
					if val != "" {
						if strings.HasPrefix(val, "%") && strings.HasSuffix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?), '%') AND ")
						} else if strings.HasPrefix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT('%', TRIM(BOTH '%' FROM ?)) AND ")
						} else if strings.HasSuffix(val, "%") {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " LIKE CONCAT(TRIM(BOTH '%' FROM ?), '%') AND ")
						} else {
							params = append(params, val)
							whereSQL0.WriteString(v.Quote(col) + " = ? AND ")
						}
					}
				}
			}
		}
		helper.JoinWhereBuilder(&generateSQL, whereSQL0)
	}

	var executeSQL *gorm.DB
	executeSQL = v.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	_ = executeSQL

	return
}

func (v videoStudioMappingDo) Debug() *videoStudioMappingDo {
	return v.withDO(v.DO.Debug())
}

func (v videoStudioMappingDo) WithContext(ctx context.Context) *videoStudioMappingDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v videoStudioMappingDo) ReadDB() *videoStudioMappingDo {
	return v.Clauses(dbresolver.Read)
}

func (v videoStudioMappingDo) WriteDB() *videoStudioMappingDo {
	return v.Clauses(dbresolver.Write)
}

func (v videoStudioMappingDo) Session(config *gorm.Session) *videoStudioMappingDo {
	return v.withDO(v.DO.Session(config))
}

func (v videoStudioMappingDo) Clauses(conds ...clause.Expression) *videoStudioMappingDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v videoStudioMappingDo) Returning(value interface{}, columns ...string) *videoStudioMappingDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v videoStudioMappingDo) Not(conds ...gen.Condition) *videoStudioMappingDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v videoStudioMappingDo) Or(conds ...gen.Condition) *videoStudioMappingDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v videoStudioMappingDo) Select(conds ...field.Expr) *videoStudioMappingDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v videoStudioMappingDo) Where(conds ...gen.Condition) *videoStudioMappingDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v videoStudioMappingDo) Order(conds ...field.Expr) *videoStudioMappingDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v videoStudioMappingDo) Distinct(cols ...field.Expr) *videoStudioMappingDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v videoStudioMappingDo) Omit(cols ...field.Expr) *videoStudioMappingDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v videoStudioMappingDo) Join(table schema.Tabler, on ...field.Expr) *videoStudioMappingDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v videoStudioMappingDo) LeftJoin(table schema.Tabler, on ...field.Expr) *videoStudioMappingDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v videoStudioMappingDo) RightJoin(table schema.Tabler, on ...field.Expr) *videoStudioMappingDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v videoStudioMappingDo) Group(cols ...field.Expr) *videoStudioMappingDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v videoStudioMappingDo) Having(conds ...gen.Condition) *videoStudioMappingDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v videoStudioMappingDo) Limit(limit int) *videoStudioMappingDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v videoStudioMappingDo) Offset(offset int) *videoStudioMappingDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v videoStudioMappingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *videoStudioMappingDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v videoStudioMappingDo) Unscoped() *videoStudioMappingDo {
	return v.withDO(v.DO.Unscoped())
}

func (v videoStudioMappingDo) Create(values ...*model.VideoStudioMapping) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v videoStudioMappingDo) CreateInBatches(values []*model.VideoStudioMapping, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v videoStudioMappingDo) Save(values ...*model.VideoStudioMapping) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v videoStudioMappingDo) First() (*model.VideoStudioMapping, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoStudioMapping), nil
	}
}

func (v videoStudioMappingDo) Take() (*model.VideoStudioMapping, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoStudioMapping), nil
	}
}

func (v videoStudioMappingDo) Last() (*model.VideoStudioMapping, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoStudioMapping), nil
	}
}

func (v videoStudioMappingDo) Find() ([]*model.VideoStudioMapping, error) {
	result, err := v.DO.Find()
	return result.([]*model.VideoStudioMapping), err
}

func (v videoStudioMappingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VideoStudioMapping, err error) {
	buf := make([]*model.VideoStudioMapping, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v videoStudioMappingDo) FindInBatches(result *[]*model.VideoStudioMapping, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v videoStudioMappingDo) Attrs(attrs ...field.AssignExpr) *videoStudioMappingDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v videoStudioMappingDo) Assign(attrs ...field.AssignExpr) *videoStudioMappingDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v videoStudioMappingDo) Joins(fields ...field.RelationField) *videoStudioMappingDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v videoStudioMappingDo) Preload(fields ...field.RelationField) *videoStudioMappingDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v videoStudioMappingDo) FirstOrInit() (*model.VideoStudioMapping, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoStudioMapping), nil
	}
}

func (v videoStudioMappingDo) FirstOrCreate() (*model.VideoStudioMapping, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VideoStudioMapping), nil
	}
}

func (v videoStudioMappingDo) FindByPage(offset int, limit int) (result []*model.VideoStudioMapping, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v videoStudioMappingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v videoStudioMappingDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v videoStudioMappingDo) Delete(models ...*model.VideoStudioMapping) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *videoStudioMappingDo) withDO(do gen.Dao) *videoStudioMappingDo {
	v.DO = *do.(*gen.DO)
	return v
}
