// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSeason = "season"

// Season 季
type Season struct {
	ID           uint64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id,string"` // 主键
	SeriesID     int64  `gorm:"column:series_id;not null;comment:连续剧id" json:"seriesId"`             // 连续剧id
	Season       int32  `gorm:"column:season;not null;comment:第几季" json:"season"`                    // 第几季
	SeriesTitle  string `gorm:"column:series_title;not null;comment:季名称" json:"seriesTitle"`         // 季名称
	SkipIntro    int64  `gorm:"column:skip_intro;comment:片头跳过秒数" json:"skipIntro"`                   // 片头跳过秒数
	SkipEnding   int64  `gorm:"column:skip_ending;comment:片尾跳过秒数" json:"skipEnding"`                 // 片尾跳过秒数
	EpisodeCount int32  `gorm:"column:episode_count;not null;comment:总集数" json:"episodeCount"`       // 总集数
}

// TableName Season's table name
func (*Season) TableName() string {
	return TableNameSeason
}
