// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideoSubtitleMapping = "video_subtitle_mapping"

// VideoSubtitleMapping 影片字幕关联表
type VideoSubtitleMapping struct {
	ID        uint64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id,string"`                                 // 主键
	VideoType string `gorm:"column:video_type;not null;comment:影片类型，movie,series,season,episode" json:"videoType"`                // 影片类型，movie,series,season,episode
	VideoID   int64  `gorm:"column:video_id;not null;comment:影片id，根据video_type类型分别来自movie,series,season,episode表" json:"videoId"` // 影片id，根据video_type类型分别来自movie,series,season,episode表
	URL       string `gorm:"column:url;not null;comment:字幕地址" json:"url"`                                                         // 字幕地址
	Title     string `gorm:"column:title;not null;comment:字幕标题" json:"title"`                                                     // 字幕标题
	Language  string `gorm:"column:language;not null;comment:字幕语言" json:"language"`                                               // 字幕语言
	MimeType  string `gorm:"column:mime_type;not null;comment:字幕格式" json:"mimeType"`                                              // 字幕格式
}

// TableName VideoSubtitleMapping's table name
func (*VideoSubtitleMapping) TableName() string {
	return TableNameVideoSubtitleMapping
}
