// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideoStudioMapping = "video_studio_mapping"

// VideoStudioMapping 影片出品方关联表
type VideoStudioMapping struct {
	ID        uint64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id,string"`                                 // 主键
	VideoType string `gorm:"column:video_type;not null;comment:影片类型，movie,series,season,episode" json:"videoType"`                // 影片类型，movie,series,season,episode
	VideoID   int64  `gorm:"column:video_id;not null;comment:影片id，根据video_type类型分别来自movie,series,season,episode表" json:"videoId"` // 影片id，根据video_type类型分别来自movie,series,season,episode表
	StudioID  int64  `gorm:"column:studio_id;not null;comment:出品方id" json:"studioId"`                                             // 出品方id
}

// TableName VideoStudioMapping's table name
func (*VideoStudioMapping) TableName() string {
	return TableNameVideoStudioMapping
}
