// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideoUserMapping = "video_user_mapping"

// VideoUserMapping 影片用户关联表
type VideoUserMapping struct {
	ID                 uint64 `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id,string"`                                 // 主键
	VideoType          string `gorm:"column:video_type;not null;comment:影片类型，movie,series,season,episode" json:"videoType"`                // 影片类型，movie,series,season,episode
	VideoID            int64  `gorm:"column:video_id;not null;comment:影片id，根据video_type类型分别来自movie,series,season,episode表" json:"videoId"` // 影片id，根据video_type类型分别来自movie,series,season,episode表
	LastPlayedPosition int64  `gorm:"column:last_played_position;comment:影片上次播放位置，第n秒" json:"lastPlayedPosition"`                          // 影片上次播放位置，第n秒
	LastPlayedTime     int64  `gorm:"column:last_played_time;comment:上次播放时候" json:"lastPlayedTime"`                                        // 上次播放时候
	Favorited          bool   `gorm:"column:favorited;not null;comment:是否收藏喜欢" json:"favorited"`                                           // 是否收藏喜欢
}

// TableName VideoUserMapping's table name
func (*VideoUserMapping) TableName() string {
	return TableNameVideoUserMapping
}
